#!/usr/bin/env bash
# file: test/js-test

if [ -z "$1" ]; then
  echo
  echo "Quick&Dirty way around to run 'truffle test test/<pattern>.spec.js'"
  echo " Before running the command it renames files which are not tested"
  echo " from test/*.spec.js into test/*.spec.js.off"
  echo " and files which are under the test"
  echo " from test/*.spec.js.off into test/*.spec.js"
  echo
  echo " usage: js-test <pattern>|\"<pattern1> <pattern2> <pattern...>\"";
  echo " example: js-tests on Token"
  echo
  exit
fi;

patterns="$1"
options="$2"

function runTest {
  ./scripts/set_js-tests off
  ./scripts/set_js-tests on "$1"
  truffle test $2
}

[ -d "test/log/" ] || mkdir test/log/

for pattern in $1; do
  logfile=test/log/${pattern}.log
  date | tee ${logfile}
  runTest "${pattern}" "${options}" | tee -a ${logfile} 2>&1
done
